
version: 2

models:
  - name: films
    description: "This table contains details about films."
    columns:
      - name: film_id
        description: "Unique identifier for the film."
        tests:
          - unique
          - not_null
      - name: title
        description: "Title of the film."
        tests:
          - not_null
      - name: release_date
        description: "Date the film was released."
        tests:
          - not_null
      - name: price
        description: "Price to buy a ticket."
        tests:
          - not_null
      - name: rating
        description: "The MPAA rating of the film."
        tests:
          - not_null
      - name: user_rating
        description: "Rating that users gave the film."
        tests:
          - not_null

  - name: actors
    description: "This table contains details about actors."
    columns:
      - name: actor_id
        description: "Unique identifier for the actor."
        tests:
          - unique
          - not_null
      - name: name
        description: "Name of the actor."
        tests:
          - not_null

  - name: film_actors
    description: "This table links films to the actors in them."
    columns:
      - name: film_id
        description: "ID of the film."
        tests:
          - not_null
      - name: actor_id
        description: "ID of the actor."
        tests:
          - not_null
